name: domotica

x-site: &base-site
  build:
    context: .
    dockerfile: Dockerfile.dev
    args: &site-env
      PYTHONUNBUFFERED: 1
      FLASK_SESSION_COOKIE_HTTPONLY: true
      FLASK_SESSION_COOKIE_SECURE: false
      FLASK_SECRET_KEY: "change-me@123!"
      DATABASE_URL: "postgresql://user:pwd123%40@db/dev"
  environment: *site-env
  ports:
    - "0.0.0.0:8080:5000"
  depends_on:
    db:
      condition: service_healthy
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:5000" ]
    interval: 30s
    timeout: 15s
    retries: 3
    start_period: 30s
    start_interval: 15s

services:
  db:
    container_name: database
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd123@
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./.db-data:/var/lib/postgresql/:rw
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} && 
              psql -U $${POSTGRES_USER} -d $${POSTGRES_DB} -c 'SELECT 1' >/dev/null 2>&1" ]
      interval: 30s
      retries: 5
      start_period: 35s
      timeout: 10s

  site-dev:
    <<: *base-site
    container_name: site-dev
    command: flask --app webserver.app run --host=0.0.0.0 --debug
    volumes:
      - site-build:/data/public:rw
      - ./webserver:/data/webserver:ro
      - ./static:/data/static:ro
    profiles:
      - dev

  site-prod:
    <<: *base-site
    container_name: site
    command: flask --app webserver.app run --host=0.0.0.0
    volumes:
      - site-build-prod:/data/public:rw
      - ./webserver:/data/webserver:ro
      - ./static:/data/static:ro
    profiles:
      - prod

volumes:
  site-build:
  site-build-prod:
