FROM python:3.14-slim-trixie

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

WORKDIR /data

COPY pyproject.toml ./
COPY build.sh ./
COPY db/ ./db/
COPY webserver/ ./webserver/
COPY static/ ./static/

RUN pip install .
RUN ./build.sh

EXPOSE 5000
ENTRYPOINT ["flask", "--app", "webserver.app", "run", "--host", "0.0.0.0"]
