FROM python:3.14-slim-trixie

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

WORKDIR /data

# Add curl for healthcheck purposes
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends curl
RUN rm -rf /var/lib/apt/lists/*

COPY pyproject.toml ./
RUN pip install .

COPY build.sh ./
COPY db/ ./db/
COPY webserver/ ./webserver/
COPY static/ ./static/

#volume to make it persist between container starts (contains mainly cached data)
VOLUME /data/public

ENTRYPOINT ["./build.sh"]
