#!/usr/bin/env bash

cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" || exit 3
cd ..

mkdir public
cp -r -t public/ static/*
cd public/ || exit 4
mv html/*.html .
rm -rf html/
cd ..
echo Prepared field correctly

mkdir -p .vercel/output/static
cp -r public/* .vercel/output/static/

echo files configured to be served from CDN:
ls -lAr .vercel/output/static/
echo end