#!/usr/bin/env bash

cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" || exit 3
cd ..

mkdir public
cp -r -t public/ static/*
cd public/ || exit 4
mv html/*.html .
rm -rf html/
cd ..
echo Prepared field correctly

mkdir -p .vercel/output/static
cp public/* .vercel/output/static/

# enable CDN serving of static files
cat >.vercel/output/config.json <<EOF
{
 "version": 3
}
EOF

echo files configured to be served from CDN:
ls -lAR .vercel/output/
echo end