name: test.yml
on:
  # placeholder
  workflow_dispatch:
#  deployment:
#  deployment_status:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - name: env vars
       run: set
     - name: some github vars
       run: |
         echo "github.event_name: " "${{ github.event_name }}"
         echo "github.event.deployment_status.state: " "${{ github.event.deployment_status.state }}"
         echo "github.event.deployment.environment: " "${{ github.event.deployment.environment }}"
         echo "github.event.deployment.environment_url: " "${{ github.event.deployment.environment_url }}"
         echo "github.event.deployment_status.target_url: " "${{ github.event.deployment_status.target_url }}"
         echo "github.event.deployment_status.type: " "${{ github.event.deployment_status.type }}"
         echo "github.event.deployment.sha: " "${{ github.event.deployment.sha }}"
         echo "github.event.deployment_status.sha: " "${{ github.event.deployment_status.sha }}"
     - name: dump context
       run: echo "${{ toJson(github) }}"
